#!/bin/bash
to=sysadmin@hz.netease.com
changes=${5##*/}
package=${changes%.*}
if echo $REPREPRO_BASE_DIR | grep -qs 'staging/$'; then
  repo="repo-staging"
else
  repo="repo"
fi
title="[$repo] $package added to $2"
mail -s "$title" $to < $5
#echo "$title" $to
#cat $5
