#!/bin/bash
apt-get install -y "${APTGETOPT[@]}" lsb-release devscripts
codename=$(lsb_release --short --codename)
case "$codename" in
	squeeze)
		dist="stable"
		;;
	lenny)
		dist="old-stable"
		;;
	*)
		dist="unstable"
		;;
esac
cd /tmp/buildd/*/debian/..
deb_version=$(dpkg-parsechangelog | awk '/^Version:/ {print $2}')
debchange --maintmaint --distribution "${dist}" --newversion "${deb_version}${codename}" "build against ${codename}"
