#!/bin/bash
#apt-get install -y "${APTGETOPT[@]}" lsb-release devscripts
codename=$(lsb_release --short --codename)
case "$codename" in
	wheezy)
		dist="testing"
		;;
	squeeze)
		dist="stable"
		;;
	lenny)
		dist="oldstable"
		;;
	*)
		dist="unstable"
		;;
esac
cd /tmp/buildd/*/debian/..
debchange --append --maintmaint --distribution "${dist}" "Build against ${codename}."
sed -i '1s/)/'${codename}')/' debian/changelog
