#!/bin/bash
if [ x"$(lsb_release --short --codename)" == x"squeeze" ]; then
    cp /etc/apt/sources.list /etc/apt/sources.list.bak
    echo "deb http://ftp.jaist.ac.jp/debian-backports squeeze-backports main" >> /etc/apt/sources.list
    apt-get update
    apt-get install -y -t squeeze-backports debhelper
    mv /etc/apt/sources.list.bak /etc/apt/sources.list
    apt-get update
fi
