#!/bin/bash
jdk=$1
mkdir /tmp/buildd/build
chown nobody\: /tmp/buildd/build
apt-get install -y java-package
su -c "
cd /tmp/buildd/build
yes | make-jpkg --changes ../${jdk}
" - nobody
cp /tmp/buildd/build/* "$BIND_DIR"
