#!/bin/bash
# TODO handle if version_append is empty
set -x
export debian_chroot="pbuilder"

pwd=$1
shift
cd "$pwd"

deb=$1
arch=$2
version_append=$3
revision_append=$4
source=$(echo $deb | awk -F_ '{print $1}')
revision=$(echo $deb | awk -F_ '{print $2}')
ncpu=$(grep -c '^processor' /proc/cpuinfo)

apt-get install -y kernel-package bc cpio libncurses-dev
dpkg -i $deb

cd ..
tar xf /usr/src/${source}.tar.*
cd ${source}
xzcat /usr/src/${source/source/config}/config.${arch}_none_${arch}.xz > .config

conf_script="/tmp/buildd/kpkg-${version_append}"
if [ -f "$conf_script" ]; then
  bash -x "$conf_script"
fi

tmp=$(mktemp -u)
cat <<EOF >build.sh
export KPKG_MAINTAINER="Zhong Jianxin"
export KPKG_EMAIL="azuwis@gmail.com"
export DELETE_BUILD_LINK=YES
fakeroot make-kpkg --jobs ${ncpu} --initrd --revision ${revision}${revision_append} --append_to_version -${version_append}-${arch} binary-arch
cd ..
dpkg-deb -R ${source/source/headers}*-${version_append}-${arch}_${revision}${revision_append}_${arch}.deb $tmp
cp -r ${source}/debian/examples/etc/kernel/header_p* ${tmp}/etc/kernel/
dpkg-deb -b ${tmp} .
EOF
chmod +x build.sh
bash -x ./build.sh
#TERM=rxvt screen </dev/tty > /dev/tty 2> /dev/tty
