#!/bin/bash
echo "#################### header_clean_hook start ####################"
set -x
HEADERS=$(basename $(pwd))
VERSION=${HEADERS/linux-headers-/}
MODULES_DIR="../../../lib/modules/${VERSION}"
mkdir -p ${MODULES_DIR}
ln -s /usr/src/${HEADERS} ${MODULES_DIR}/build
ln -s /usr/src/${HEADERS} ${MODULES_DIR}/source
set +x
echo "#################### header_clean_hook end   ####################"
